package com.moraes;
// Generated 22/02/2018 17:49:32 by Hibernate Tools 4.3.5.Final


/**
 * PagamentoId generated by hbm2java
 */
public class PagamentoId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private long cpf;
	private long cdcurso;

	public PagamentoId() {}

	public PagamentoId(long cpf, long cdcurso) {
		this.cpf = cpf;
		this.cdcurso = cdcurso;
	}
	
	public PagamentoId(PagamentoId objeto) {
		this.cpf = objeto.cpf;
		this.cdcurso = objeto.cdcurso;
	}

	public long getCpf() {
		return this.cpf;
	}

	public void setCpf(long cpf) {
		this.cpf = cpf;
	}

	public long getCdcurso() {
		return this.cdcurso;
	}

	public void setCdcurso(long cdcurso) {
		this.cdcurso = cdcurso;
	}

	@Override
	public String toString() {
		return "PagamentoId CPF == " + cpf + ", Código do Curso == " + cdcurso;
	}
}
